### ISSUE TITLE
App is crashing at app database initialization

### ISSUE THREAD

**Issue by rushabhshah065** [ueen/RoomAsset#1]
I am getting this crash by using your fork

Unable to create application .ApplicationClass: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer

At here : 
appDatabase = RoomAsset.databaseBuilder(getApplicationContext(),
AppDatabase.class, "dbname.db",3).
addMigrations(MIGRATION_1_2,MIGRATION_2_3).allowMainThreadQueries().build();

My migration class

static final Migration MIGRATION_1_2 = new Migration(1, 2) {
    @Override
    public void migrate(SupportSQLiteDatabase database) {
        // Since we didn't alter the table, there's nothing else to do here.
    }
};

static final Migration MIGRATION_2_3 = new Migration(2, 3) {
    @Override
    public void migrate(SupportSQLiteDatabase database) {
        // Since we didn't alter the table, there's nothing else to do here.
    }
};
I have already file extension and migration as needed in my code. Until it is crashing.

  java.lang.RuntimeException: Unable to create application 
.ApplicationClass: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5954)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
        at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:302)
        at com.huma.room_for_asset.RoomAsset$Companion.openDb(RoomAsset.kt:62)
        at com.huma.room_for_asset.RoomAsset$Companion.databaseBuilder(RoomAsset.kt:45)
        at com.huma.room_for_asset.RoomAsset.databaseBuilder(Unknown Source:2)
        at 
ApplicationClass.onCreate(ApplicationClass.java:59)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)

**Comment by ueen** [comment]
Ok I know what the problem is, you should be able to solve it by reinstalling the app, but for convenience I also provided a fix, please upgrade the implementation 'com.github.ueen:RoomAsset:1.1.9'

**Comment by rushabhshah065** [comment]
Yup in 1.1.9 version its work fine!! Thanks.
